### ISSUE TITLE
Make auth flow work with https://oidcdebugger.com

### ISSUE THREAD

**Issue by arshadali172** [datagovsg/singpasspass#10]

**Comment by cloudhary** [comment]
https://openid.net/specs/openid-financial-api-jarm-wd-01.html#response-mode-query.jwt

Not going to bother with setting this up @arshadali172, since it's a minor configuration that I don't fully understand the implications of. I propose that we just use https://openidconnect.net/

**Comment by cloudhary** [comment]
Works with postman, not necessary or important
